# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - Sales-App-Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build FluorSalesApp.sln --configuration Release
        working-directory: ./SalesApp/FluorAssesment/FlourSales-API/FluorSalesApp/FluorSalesApp.sln
        
      - name: dotnet publish
        run: dotnet publish FluorSalesApp.sln -c Release -o "${{env.DOTNET_ROOT}}/myapp"
        working-directory: SalesApp/FluorAssesment/FlourSales-API/FluorSalesApp/FluorSalesApp.sln

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2C90B21527B04E6DAD8C4F980D943ECF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C4727F99FEFB401AB907AF0BFA4DAAE0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BA8D8DD552164348AA9CFF54CFE94FFD }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Sales-App-Test'
          slot-name: 'Production'
          package: .

          



